package exceptionHandling;

public class ExceptonHandling {

	public static void main(String[] args) {
		int value[] = {3,6,8,4,9};
		try {
			System.out.println(value[1/0]);
			System.out.println(value[6]);
		} catch (Exception e) {
			System.out.println(e);
		}
		System.out.println("Program is successful");

	}

}
